baseURL = "https://wolfgang61.github.io/rl-digital-api-docs/"
title = "RL Digital API Documentation"

defaultContentLanguage = "de"

enableRobotsTXT = true
enableGitInfo = true

[params]
  copyright = "RL Digital"
  github_repo = "https://github.com/Wolfgang61/rl-digital-api-docs"
  github_project_repo = "https://github.com/Wolfgang61/rl-digital-api-docs"

  offlineSearch = true

  [params.ui]
    
    sidebar_menu_compact = true
    sidebar_search_disable = false
    breadcrumb_disable = false

[markup]
  [markup.goldmark.renderer]
    unsafe = true

  [markup.highlight]
    noClasses = false
    style = "github"
    lineNos = false

[outputs]
  home = ["HTML"]

[taxonomies]
  category = "categories"
  tag = "tags"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.146.0"

  [[module.imports]]
    path = "github.com/google/docsy"