name: CI and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.167.0'
          extended: true

      - name: Install Python dependencies
        run: |
          python3 -m pip install -r scripts/requirements.txt

      - name: Install NPM dependencies
        run: |
          npm install

      - name: Sync Hugo NPM dependencies
        run: |
          hugo mod npm pack
          npm install

      - name: Validate OpenAPI specs
        run: |
          npm run validate:openapi

      - name: Check content
        run: |
          npm run check:content

      - name: Show Hugo config
        run: |
          cat hugo.toml
      
      - name: Debug content
        run: |
          echo "===== CONTENT ====="
          find content -type f | sort

          echo "===== DOCS ====="
          find content/de/docs -type f | sort || true

          echo "===== HUGO CONFIG ====="
          hugo config | grep -E "defaultContentLanguage|contentDir|theme"


      - name: Build website
        run: |
          hugo --gc --minify

      - name: Show generated files
        run: |
          find public -maxdepth 3 -type f | sort

      - name: Debug site
        run: |
          echo "===== INDEX ====="
          find public -name "index.html"

          echo "===== DOCS ====="
          find public/docs -type f || true

          echo "===== ALL FILES ====="
          find public -type f | sort


      - name: Debug output
        run: |
          pwd
          ls -la
          ls -la public
          ls -la public/docs

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    if: github.ref == 'refs/heads/main'

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4